distrib_system/distrib_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.autoredirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('userroles.urls')),
    url(r'^distribution/', include('choose_distrib.urls')),
]

distrib_system/userroles/urls.py
from django.conf.urls import url
from . import views

app_name = 'userroles'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.new_login, name='login'),
    url(r'^logout/$', views.new_logout, name='logout'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/$', views.my_profile, name='profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editprof/$', views.edit_profile, name='edit_profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editpass/$', views.edit_password, name='edit_password'),
]

distrib_system/userroles/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    group = models.CharField(max_length=10, blank=True)
    course = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.user.__str__()


class Cooperator(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    work = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class Professor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class ScientificDirector(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()

distrib_system/userroles/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    POSITIONS = (
        ('student', 'Студент'),
        ('professor', 'Преподаватель'),
        ('cooperator', 'Сотрудник'),
        ('scientific_director', 'Научный руководитель'),
    )
    username = forms.CharField(max_length=50, label="Имя пользователя")
    last_name = forms.CharField(max_length=50, required=True, label="Фамилия")
    first_name = forms.CharField(max_length=50, required=True, label="Имя")
    position = forms.MultipleChoiceField(required=True, choices=POSITIONS, widget=forms.CheckboxSelectMultiple())
    email = forms.EmailField(widget=forms.EmailInput, label="Электронная почта")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    pass2 = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль")

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

distrib_system/userroles/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .utils import *

# Create your views here.


def register(request):
    if request.method == "POST":
        user = User(username=request.POST['username'])
        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        try:
            user.save()
        except IntegrityError:
            messages.add_message(request, messages.INFO, 'Этот логин занят')
            return render(request, 'login.html')
        positions = request.POST.getlist('position')
        initialize_user(user, positions)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.add_message(request, messages.INFO, 'Incorrect')
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                messages.add_message(request, messages.INFO, 'Your account is not active')
    return render(request, 'register.html')


def new_login(request):
    if request.POST:
        username = request.POST.get('login')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                raise Http404
        else:
            messages.add_message(request, messages.INFO, 'Неправильный логин или пароль')
            messages.get_messages(request)
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')


def new_logout(request):
    
    logout(request)
    return HttpResponseRedirect('/accounts/login/')
                

@login_required(login_url='/accounts/login')
def base_context(request):
    user = request.user
    is_student = get_entity_from_db(user, 'Student')
    is_cooperator = get_entity_from_db(user, 'Cooperator')
    is_professor = get_entity_from_db(user, 'Professor')
    is_sci_director = get_entity_from_db(user, 'ScientificDirector')
    context = {
        "user_id": user.id,
        "user_surname": user.last_name,
        "user_name": user.first_name,
        "user_email": user.email,
        "user_username": user.username,
        "is_student": is_student,
        "is_professor": is_professor,
        "is_cooperator": is_cooperator,
        "is_sci_director": is_sci_director
    }
    return context


@login_required(login_url='/accounts/login')
def my_profile(request, user_id):
    return render(request, "accounts/parts/my_data.html", base_context(request))


@login_required(login_url='/accounts/login')
def edit_profile(request, user_id):
    user = request.user
    if request.POST["user_new_name"] is not "":
        user.first_name = request.POST["user_new_name"]
    if request.POST["user_new_surname"] is not "":
        user.last_name = request.POST["user_new_surname"]
    if request.POST["user_new_username"] is not "":
        user.username = request.POST["user_new_username"]
    if request.POST["user_new_email"] is not "":
        user.email = request.POST["user_new_email"]
    user.save()
    return my_profile(request, user_id)


@login_required(login_url='/accounts/login')
def edit_password(request, user_id):    
    user = request.user

distrib_system/userroles/templates/accounts/my_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ user_name }} - DistribSystem</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- Bootstrap -->
    <link href="{% static 'userroles/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'userroles/css/style.css' %}">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'userroles/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-targer="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'userroles:profile' user_id %}" >Добро пожаловать, {{ user_name }} {{ user_surname }}!</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'userroles:profile' user_id %}">Мой профиль</a>
            </li>
          </ul>
          <form class="navbar-form navbar-right" action="{% url 'userroles:logout' %}">
            <button class="btn btn-primary" type="submit">Выйти</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row content">
        <div class="col-sm-3 sidenav">
          <img class="image-padding" src="{% static "userroles/img/profile_logo.svg" %}">
          <div class="list-group">
            <br><br>
            {% if is_student %}
              {% include "accounts/parts/menus/student_menu.html" %}
            {% endif %}

            {% if is_professor %}
              {% include "accounts/parts/menus/professor_menu.html" %}
            {% endif %}
            
            {% if is_cooperator %}
              {% include "accounts/parts/menus/cooperator_menu.html" %}
            {% endif %}
            
            {% if is_sci_director %}
              {% include "accounts/parts/menus/sci_dir_menu.html" %}  
            {% endif %}
          </div>
        </div>
        <div class="col-sm-9">
          <h4><small>Домашняя</small></h4>
          <hr>
          <!-- Здесь рисовать данные или таблицу практик или запросов -->
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <footer class="container-fluid">
      <p>DistribSystem Team (c) 2017</p>
    </footer>
  </body>
</html>