distrib_system/choose_distrib/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'choose_distrib'
urlpatterns = [
    url(r'^my_profile/(?P<user_id>[0-9]+)/', 
    include([
        url(r'^student/', 
        include([
            url(r'^(?P<container_type>[A-z]+)/(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/$', views.student_make_request, name='student_make_request'), 
            url(r'^(?P<container_type>[A-z]+)/$', views.student_form, name='student')])),                                          
        url(r'^professor/', 
        include([
            url(r'^(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/(?P<user_id2>[0-9]+)/(?P<request_status>[1-2])/$', views.professor_request_change_status, name='professor_request_change_status'),
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.professor_form, name='professor')])),
        url(r'^sc_dir/', 
        include([ 
            url(r'^(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/(?P<user_id2>[0-9]+)/(?P<request_status>[1-2])/$', views.sc_dir_request_change_status, name='sc_dir_request_change_status')])),
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.sci_dir_form, name='sc_dir_sci_dir'),
        url(r'^cooperator/', 
        include([
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.coop_form, name='cooperator')]))
        ]))]

distrib_system/distrib_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.autoredirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('userroles.urls')),
    url(r'^distribution/', include('choose_distrib.urls')),
]

distrib_system/userroles/urls.py
from django.conf.urls import url
from . import views

app_name = 'userroles'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.new_login, name='login'),
    url(r'^logout/$', views.new_logout, name='logout'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/$', views.my_profile, name='profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editprof/$', views.edit_profile, name='edit_profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editpass/$', views.edit_password, name='edit_password'),
]

distrib_system/userroles/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    group = models.CharField(max_length=10, blank=True)
    course = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.user.__str__()


class Cooperator(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    work = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class Professor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class ScientificDirector(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()

distrib_system/userroles/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    POSITIONS = (
        ('student', 'Студент'),
        ('professor', 'Преподаватель'),
        ('cooperator', 'Сотрудник'),
        ('scientific_director', 'Научный руководитель'),
    )
    username = forms.CharField(max_length=50, label="Имя пользователя")
    last_name = forms.CharField(max_length=50, required=True, label="Фамилия")
    first_name = forms.CharField(max_length=50, required=True, label="Имя")
    position = forms.MultipleChoiceField(required=True, choices=POSITIONS, widget=forms.CheckboxSelectMultiple())
    email = forms.EmailField(widget=forms.EmailInput, label="Электронная почта")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    pass2 = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль")

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

distrib_system/userroles/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .utils import *

# Create your views here.


def register(request):
    if request.method == "POST":
        user = User(username=request.POST['username'])
        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        try:
            user.save()
        except IntegrityError:
            messages.add_message(request, messages.INFO, 'Этот логин занят')
            return render(request, 'login.html')
        positions = request.POST.getlist('position')
        initialize_user(user, positions)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.add_message(request, messages.INFO, 'Incorrect')
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                messages.add_message(request, messages.INFO, 'Your account is not active')
    return render(request, 'register.html')


def new_login(request):
    if request.POST:
        username = request.POST.get('login')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                raise Http404
        else:
            messages.add_message(request, messages.INFO, 'Неправильный логин или пароль')
            messages.get_messages(request)
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')


def new_logout(request):
    
    logout(request)
    return HttpResponseRedirect('/accounts/login/')
                

@login_required(login_url='/accounts/login')
def base_context(request):
    user = request.user
    is_student = get_entity_from_db(user, 'Student')
    is_cooperator = get_entity_from_db(user, 'Cooperator')
    is_professor = get_entity_from_db(user, 'Professor')
    is_sci_director = get_entity_from_db(user, 'ScientificDirector')
    context = {
        "user_id": user.id,
        "user_surname": user.last_name,
        "user_name": user.first_name,
        "user_email": user.email,
        "user_username": user.username,
        "is_student": is_student,
        "is_professor": is_professor,
        "is_cooperator": is_cooperator,
        "is_sci_director": is_sci_director
    }
    return context


@login_required(login_url='/accounts/login')
def my_profile(request, user_id):
    return render(request, "accounts/parts/my_data.html", base_context(request))


@login_required(login_url='/accounts/login')
def edit_profile(request, user_id):
    user = request.user
    if request.POST["user_new_name"] is not "":
        user.first_name = request.POST["user_new_name"]
    if request.POST["user_new_surname"] is not "":
        user.last_name = request.POST["user_new_surname"]
    if request.POST["user_new_username"] is not "":
        user.username = request.POST["user_new_username"]
    if request.POST["user_new_email"] is not "":
        user.email = request.POST["user_new_email"]
    user.save()
    return my_profile(request, user_id)


@login_required(login_url='/accounts/login')
def edit_password(request, user_id):    
    user = request.user

distrib_system/userroles/templates/accounts/parts/container_table.html
{% extends 'accounts/my_profile.html' %}
{% block content %}

<table border="1">
  <caption>Таблица контейнеров</caption>

  <tr>
    <th>Название</th>
    <th>Руководитель</th>
    <th>Занято/Всего</th>
    <th>Действия</th>
    <th>Состояние</th>
  </tr>
    {% for content in triples %}
  <tr>

      <td> {{ content.first_item.container_name }} </td>
      <td> 
          {% for director in content.first_item.container_director.all %}
                {{ director.first_name }} {{ director.last_name }}<br>{{ director.email }}
          {% endfor %}
      </td>
      <td> {{ content.second_item }} / {{ content.first_item.container_capacity }} </td>
      <td>
          <form action={% url 'choose_distrib:student_make_request' user_id content.first_item.container_type content.first_item.container_type content.first_item.id %}  method="post">
            {% csrf_token %}
            <input type="submit" name="decline" value="Подать заявку">
          </form>
      </td>
      <td>
        {% if content.third_item %}
              {% if content.third_item.pop.status == 0 %}
                  Рассматривается
              {% elif content.third_item.pop.status == 1 %}
                  Принята
              {% elif content.third_item.pop.status == 2 %}
                  Отклонена
              {% endif %}
         {% else %}
          Нет
         {% endif %}
      </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

distrib_system/userroles/templates/accounts/parts/my_data.html
{% extends 'accounts/my_profile.html' %}

{% block content %}
<div class="col col-lg-5">
  <h2>Ваши данные:</h2>
  <form class="form-changing" method="post" action="{% url 'userroles:edit_profile' user_id %}">
    {% csrf_token %}
    <ul class="list-group">
      <li class="list-group-item">{{user_name}} </li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Изменить имя" id="inputName" name="user_new_name">
      </li>
      <li class="list-group-item">{{user_surname}}</li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Изменить фамилию" id="inputSurname" name="user_new_surname">
      </li>
      <li class="list-group-item">{{user_username}} </li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Изменить username" id="inputUsername" name="user_new_username">
      </li>
      <li class="list-group-item">{{user_email}} </li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Изменить email" id="inputEmail" name="user_new_email">
      </li>

      <li class="list-group-item">
        <button class="btn btn-primary btn-default btn-block" type="submit">Подтвердить изменение профиля</button>
      </li>

    </ul>  
  </form>
  <hr>
  <h2>Сменить пароль:</h2>
  <form class="form-changing" method="post" action="{% url 'userroles:edit_password' user_id %}">
    {% csrf_token %}
    <ul class="list-group">
      <li class="list-group-item">Изменить пароль:</li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Старый пароль" id="inputOldPass" name="user_old_pass">
      </li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Новый пароль" id="inputNewPass" name="user_new_pass">
      </li>
      <li class="list-group-item">
        <input class="form-control" type="text" placeholder="Повторите Новый пароль" id="inputNewPassConfirm" name="user_new_pass_confirm">
      </li>
      <li class="list-group-item">
        <button class="btn btn-primary btn-default btn-block" type="submit">Подвердить смену пароля</button>
      </li>
    </ul>
  </form>
</div>
{% endblock %}

distrib_system/userroles/templates/accounts/parts/print_template.html
<table border="1">
  <caption>Таблица реквестов</caption>
  
  <tr>
    <th>Кто подал реквест</th>
    <th>Название контейнера</th>
    <th>Статус</th>
  </tr>
  <tr>
  {% for list in requests %}
        {% for req in list %}
        <td> {{ req.student.first_name }} {{ req.student.last_name }}<br>{{ req.student.email }}</td>
        <td> {{ req.container }} </td>
        <td> {% if req.status == 0 %}
                    Рассматривается
                {% elif req.status == 1 %}
                    Принята
                {% elif req.status == 2 %}
                    Отклонена
                {% endif %} 
        </td>
    <tr/>
        {% endfor %}
  {% endfor %}
</table>

distrib_system/userroles/templates/accounts/parts/request_already_exist.html
{% extends 'accounts/my_profile.html' %}
{% block content %}
    <caption>Сорян дагарой, ты ужо подал заявочку))))))</caption>
{% endblock%}

distrib_system/userroles/templates/accounts/parts/requests_table_with_buttons.html
{% extends 'accounts/my_profile.html' %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">Все запросы</div>
  {% if requests %}
    <table class="table table-hover">
      <thead>
          <tr>
            <th class="col-sm-1 bg-primary"></th>
            <th class="col-lg-4 bg-primary th-align-and-text-size">ФИО Студента</th>
            <th class="col-lg-4 bg-primary th-align-and-text-size">Деятельность</th>
            <th class="col-lg-4 bg-primary"></th>
          </tr>
      </thead>
      <tbody class="table-striped">
          {% for list in requests %}
            {% for req in list %}
              <tr>
                <th scope="row" align="center"></th>
                <td align="center"><span id="space">{{ req.student.first_name }} {{ req.student.last_name }}<br>{{ req.student.email }}</span></td>
                <td align="center">{{ req.container }}</td>
                <td>
                  <div align="center" id="butn{{ req.id }}">
                    <div class="col-lg-4">
                      <form action="{% url 'choose_distrib:professor_request_change_status'  user_id   req.request_type   req.container.id   req.student.id   1 %}" method="post">
                        {% csrf_token %}  
                        <button type="submit" id="success{{ req.id }}" value="Принять" name="accept" name="decline" class="btn btn-success">Принять</button>
                      </form>
                    </div>
                    <div class="col-lg-4">
                      <form action="{% url 'choose_distrib:professor_request_change_status'  user_id   req.request_type   req.container.id   req.student.id   2 %}" method="post">
                        {% csrf_token %}
                        <button type="submit" id="cancel{{ req.id }}" value="Отклонить" name="decline" class="btn btn-danger">Отклонить</button>
                      </form>
                    </div>
                  </div>
                </td>
              </tr>
              <script type="text/javascript">
                {% if req.status == 1 %}
                  document.getElementById('butn{{ req.id }}').innerHTML = '<p>Принято</p>';
                {% elif req.status == 2 %}
                  document.getElementById('butn{{ req.id }}').innerHTML = '<p>Отклонено</p>';
                {% else %}
                  document.getElementById('butn{{ req.id }}').innerHTML = '<p>Неверный статус реквеста: {{ req.status }}</p>';
                {% endif %}
              </script>
            {% endfor %}
          {% endfor %}
      </tbody>
    </table>
  {% else %}
    <h2>На текущий момент нет запросов.</h2>
  {% endif %}
</div>
{% endblock %}

distrib_system/userroles/templates/accounts/parts/requests_table_without_buttons.html
{% extends 'accounts/my_profile.html' %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">Все запросы</div>
  <table class="table table-hover">
    <thead>
        <tr>
          <th class="col-sm-1 bg-primary"></th>
          <th class="col-lg-4 bg-primary th-align-and-text-size">ФИО Студента</th>
          <th class="col-lg-4 bg-primary th-align-and-text-size">Лаборатория</th>
          <th class="col-lg-4 bg-primary th-align-and-text-size">Статус</th>
        </tr>
    </thead>
    <tbody class="table-striped">
        {% for list in requests %}
          {% for req in list %}
            <tr>
              <th scope="row" align="center">1</th>
              <td align="center"><span id="space">{{ req.student.first_name }} {{ req.student.last_name }}<br>{{ req.student.email }}</span></td>
              <td align="center">{{ req.container }}</td>
              <td>
                <div id="space">
                  {% if req.status is 0 %}
                    <p>Рассматривается</p>
                  {% elif req.status is 1 %}
                    <p>Принято</p>
                  {% elif req.status is 2 %}
                    <p>Отказано</p>
                  {% else %}
                    <p>Неверный код запроса: {{ req.status }}</p>
                  {% endif %}
                </div>
              </td>
            </tr>
          {% endfor %}
        {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}