distrib_system/choose_distrib/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'choose_distrib'
urlpatterns = [
    url(r'^my_profile/(?P<user_id>[0-9]+)/', 
    include([
        url(r'^student/', 
        include([
            url(r'^(?P<container_type>[A-z]+)/(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/$', views.student_make_request, name='student_make_request'), 
            url(r'^(?P<container_type>[A-z]+)/$', views.student_form, name='student')])),                                          
        url(r'^professor/', 
        include([
            url(r'^(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/(?P<user_id2>[0-9]+)/(?P<request_status>[1-2])/$', views.professor_request_change_status, name='professor_request_change_status'),
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.professor_form, name='professor')])),
        url(r'^sc_dir/', 
        include([ 
            url(r'^(?P<request_type>[A-z]+)/(?P<container_id>[0-9]+)/(?P<user_id2>[0-9]+)/(?P<request_status>[1-2])/$', views.sc_dir_request_change_status, name='sc_dir_request_change_status')])),
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.sci_dir_form, name='sc_dir_sci_dir'),
        url(r'^cooperator/', 
        include([
            url(r'^(?P<request_type>[A-z]+)/(?P<action_type>[A-z]+)$', views.coop_form, name='cooperator')]))
        ]))]

distrib_system/distrib_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.autoredirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('userroles.urls')),
    url(r'^distribution/', include('choose_distrib.urls')),
]

distrib_system/userroles/urls.py
from django.conf.urls import url
from . import views

app_name = 'userroles'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.new_login, name='login'),
    url(r'^logout/$', views.new_logout, name='logout'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/$', views.my_profile, name='profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editprof/$', views.edit_profile, name='edit_profile'),
    url(r'^my_profile/(?P<user_id>[0-9]+)/editpass/$', views.edit_password, name='edit_password'),
]

distrib_system/userroles/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    group = models.CharField(max_length=10, blank=True)
    course = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.user.__str__()


class Cooperator(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    work = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class Professor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()


class ScientificDirector(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    education_course = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.__str__()

distrib_system/userroles/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    POSITIONS = (
        ('student', 'Студент'),
        ('professor', 'Преподаватель'),
        ('cooperator', 'Сотрудник'),
        ('scientific_director', 'Научный руководитель'),
    )
    username = forms.CharField(max_length=50, label="Имя пользователя")
    last_name = forms.CharField(max_length=50, required=True, label="Фамилия")
    first_name = forms.CharField(max_length=50, required=True, label="Имя")
    position = forms.MultipleChoiceField(required=True, choices=POSITIONS, widget=forms.CheckboxSelectMultiple())
    email = forms.EmailField(widget=forms.EmailInput, label="Электронная почта")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    pass2 = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль")

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

distrib_system/userroles/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .utils import *

# Create your views here.


def register(request):
    if request.method == "POST":
        user = User(username=request.POST['username'])
        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        try:
            user.save()
        except IntegrityError:
            messages.add_message(request, messages.INFO, 'Этот логин занят')
            return render(request, 'login.html')
        positions = request.POST.getlist('position')
        initialize_user(user, positions)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.add_message(request, messages.INFO, 'Incorrect')
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                messages.add_message(request, messages.INFO, 'Your account is not active')
    return render(request, 'register.html')


def new_login(request):
    if request.POST:
        username = request.POST.get('login')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/accounts/my_profile/' + str(user.id))
            else:
                raise Http404
        else:
            messages.add_message(request, messages.INFO, 'Неправильный логин или пароль')
            messages.get_messages(request)
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')


def new_logout(request):
    
    logout(request)
    return HttpResponseRedirect('/accounts/login/')
                

@login_required(login_url='/accounts/login')
def base_context(request):
    user = request.user
    is_student = get_entity_from_db(user, 'Student')
    is_cooperator = get_entity_from_db(user, 'Cooperator')
    is_professor = get_entity_from_db(user, 'Professor')
    is_sci_director = get_entity_from_db(user, 'ScientificDirector')
    context = {
        "user_id": user.id,
        "user_surname": user.last_name,
        "user_name": user.first_name,
        "user_email": user.email,
        "user_username": user.username,
        "is_student": is_student,
        "is_professor": is_professor,
        "is_cooperator": is_cooperator,
        "is_sci_director": is_sci_director
    }
    return context


@login_required(login_url='/accounts/login')
def my_profile(request, user_id):
    return render(request, "accounts/parts/my_data.html", base_context(request))


@login_required(login_url='/accounts/login')
def edit_profile(request, user_id):
    user = request.user
    if request.POST["user_new_name"] is not "":
        user.first_name = request.POST["user_new_name"]
    if request.POST["user_new_surname"] is not "":
        user.last_name = request.POST["user_new_surname"]
    if request.POST["user_new_username"] is not "":
        user.username = request.POST["user_new_username"]
    if request.POST["user_new_email"] is not "":
        user.email = request.POST["user_new_email"]
    user.save()
    return my_profile(request, user_id)


@login_required(login_url='/accounts/login')
def edit_password(request, user_id):    
    user = request.user

distrib_system/userroles/templates/accounts/parts/menus/cooperator_menu.html
<h5>Сотруднику</h5>
<a href="{% url 'choose_distrib:cooperator' user_id 'Practice' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Практика</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'Practice' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные по практике</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'Course' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Курс по выбору</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'Course' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для курса по выбору</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'ScienceHead' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Курсовые работы</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'ScienceHead' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для курсовых работ</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'Laboratory' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Лаборатории</p>
</a>
<a href="{% url 'choose_distrib:cooperator' user_id 'Laboratory' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для лабораторий</p>
</a>

distrib_system/userroles/templates/accounts/parts/menus/professor_menu.html
<h5>Преподавателю</h5>
<a href="{% url 'choose_distrib:professor' user_id 'Practice' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Практика</p>
</a>
<a href="{% url 'choose_distrib:professor' user_id 'Practice' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные по практике</p>
</a>
<a href="{% url 'choose_distrib:professor' user_id 'Course' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Курс по выбору</p>
</a>
<a href="{% url 'choose_distrib:professor' user_id 'Course' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для курса по выбору</p>
</a>
<a href="{% url 'choose_distrib:professor' user_id 'Laboratory' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Лаборатории</p>
</a>
<a href="{% url 'choose_distrib:professor' user_id 'Laboratory' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для лаборатории</p>
</a>

distrib_system/userroles/templates/accounts/parts/menus/sci_dir_menu.html
<h5>Научному руководителю</h5>
<a href="{% url 'choose_distrib:sc_dir_sci_dir' user_id 'ScienceHead' 'view_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Курсовые работы</p>
</a>
<a href="{% url 'choose_distrib:sc_dir_sci_dir' user_id 'ScienceHead' 'print_requests'%}" class="list-group-item">
    <p class="list-group-item-text">Распечатать данные для курсовых работ</p>
</a>